---

- name: elf-recreate
  when: svc_elf__reg_compose_dest.stat.exists | d( true )
  ansible.builtin.command:
    cmd:    "docker compose up -d  --force-recreate"
    chdir:  "{{ svc_elf__compose_dest }}"
  become: yes
  become_user:  "{{ ansible_user }}"

